-- AlterTable
ALTER TABLE "GeoLocationSource" ALTER COLUMN "accuracy" SET DATA TYPE DOUBLE PRECISION,
ALTER COLUMN "latitude" SET DATA TYPE DOUBLE PRECISION,
ALTER COLUMN "longitude" SET DATA TYPE DOUBLE PRECISION;
